eShopMobile.AdminApp/Components/PagerViewComponent.cs
using eShopMobile.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopMobile.AdminApp.Components
{
    public class PagerViewComponent:ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default",result));
        }
    }
}

eShopMobile.AdminApp/Controllers/CategoryController.cs
using eShopMobile.ApiIntegration;
using eShopMobile.Ultilities.Constants;
using eShopMobile.ViewModels.Catalog.Categories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopMobile.AdminApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoryController(IConfiguration configuration,
            ICategoryApiClient categoryApiClient)
        {
            _configuration = configuration;
            _categoryApiClient = categoryApiClient;
        }
        public async Task<IActionResult> Index(string keyword, int? categoryId, int pageIndex = 1, int pageSize = 2)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var request = new GetManageCategoryPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                LanguageId = languageId
            };
            var data = await _categoryApiClient.GetPagings(request);
            //var data = await _categoryApiClient.GetAll(languageId);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] CategoryCreateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _categoryApiClient.CreateCategory(request);
            if (result)
            {
                TempData["result"] = "Thêm mới sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm sản phẩm thất bại");
            return View(request);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var category = await _categoryApiClient.GetById(languageId,id);
            var editVm = new CategoryUpdateRequest()
            {
                Id = category.Id,
                Name = category.Name,
                SeoAlias = category.SeoAlias,
                SeoDescription = category.SeoDescription,
                SeoTitle = category.SeoTitle,
                ParentId=category.ParentId,
                SortOrder = category.SortOrder
            };
            return View(editVm);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit([FromForm] CategoryUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _categoryApiClient.UpdateCategory(request);
            if (result)
            {
                TempData["result"] = "Cập nhật sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhật sản phẩm thất bại");
            return View(request);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(new CategoryDeleteRequest()
            {
                Id = id
            });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CategoryDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _categoryApiClient.DeleteCategory(request.Id);
            if (result)
            {
                TempData["result"] = "Xóa sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Xóa không thành công");
            return View(request);
        }
        [HttpGet]
        public async Task<ActionResult> Detail(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var result = await _categoryApiClient.GetById(languageId,id);
            return View(result);
        }
    }
}

eShopMobile.AdminApp/Views/Category/Create.cshtml
@model eShopMobile.ViewModels.Catalog.Categories.CategoryCreateRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txt_details'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}

<div class="container-fluid">
    <h1 class="mt-4">Tạo mới danh mục sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang Chủ</a></li>
        <li class="breadcrumb-item active">Tạo mới danh mục sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Category">Về danh sách danh mục</a>
        </div>
        <div class="card-body">
            <div class="col-md-8">
                <form asp-action="Create" enctype="multipart/form-data" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoDescription" class="control-label"></label>
                        <input asp-for="SeoDescription" class="form-control" />
                        <span asp-validation-for="SeoDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoTitle" class="control-label"></label>
                        <input asp-for="SeoTitle" class="form-control" />
                        <span asp-validation-for="SeoTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoAlias" class="control-label"></label>
                        <input asp-for="SeoAlias" class="form-control" />
                        <span asp-validation-for="SeoAlias" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SortOrder" class="control-label"></label>
                        <input asp-for="SortOrder" class="form-control" />
                        <span asp-validation-for="SortOrder" class="text-danger"></span>
                    </div>
                   
                    
                    <div class="form-group">
                        <input type="submit" value="Tạo mới" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopMobile.AdminApp/Views/Category/Delete.cshtml
@model eShopMobile.ViewModels.Catalog.Categories.CategoryDeleteRequest

@{
    ViewData["Title"] = "Xóa danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Xóa danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Xóa danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Category">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input asp-for="Id" type="hidden" />
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

eShopMobile.AdminApp/Views/Category/Detail.cshtml
@model eShopMobile.ViewModels.Catalog.Categories.CategoryViewModel

@{
    ViewData["Title"] = "Chi tiết";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Chi tiết</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Chi tiết</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Category">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SeoDescription)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SeoDescription)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SeoAlias)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SeoAlias)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SeoTitle)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SeoTitle)
                    </dd>
                    
                </dl>
            </div>
        </div>
    </div>
</div>

eShopMobile.AdminApp/Views/Category/Edit.cshtml
@model eShopMobile.ViewModels.Catalog.Categories.CategoryUpdateRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txt_details'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Cập nhật danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Cập nhật danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Category">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-8">
                <form asp-action="Edit" enctype="multipart/form-data" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="SeoDescription" class="control-label"></label>
                        <input asp-for="SeoDescription" class="form-control" />
                        <span asp-validation-for="SeoDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoTitle" class="control-label"></label>
                        <input asp-for="SeoTitle" class="form-control" />
                        <span asp-validation-for="SeoTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoAlias" class="control-label"></label>
                        <input asp-for="SeoAlias" class="form-control" />
                        <span asp-validation-for="SeoAlias" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
            <label asp-for="SortOrder" class="control-label"></label>
            <input asp-for="SortOrder" class="form-control" />
            <span asp-validation-for="SortOrder" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ParentId" class="control-label"></label>
            <input asp-for="ParentId" class="form-control" />
            <span asp-validation-for="ParentId" class="text-danger"></span>
        </div>*@

                    <div class="form-group">
                        <input type="submit" value="Cập nhật" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopMobile.AdminApp/Views/Category/Index.cshtml
@using eShopMobile.ViewModels.Common;
@model PagedResult<eShopMobile.ViewModels.Catalog.Categories.CategoryViewModel>

@{
    ViewData["Title"] = "List Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);

    </script>
}

<div class="container-fluid px-4">
    <h1 class="mt-4">Danh sách danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách danh mục</li>
    </ol>

    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-9">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Category">
                        Create New
                    </a>
                </div>
                <div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-4">
                                <input type="text" value="@ViewBag.Keyword" name="Keyword" class="form-control" />
                            </div>
                           
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-primary">Search</button>
                                <button type="button" onclick="window.location.href='/Category/Index'" class="btn btn-dark">Reset</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>

        </div>
        <div class="card-body">
            <div class="row">

                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }

            </div>

            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                SKU
                            </th>
                            <th>
                                Product Name
                            </th>
                            <th>
                                Description
                            </th>
                            <th>
                                Parent Id
                            </th>
                            

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SeoDescription)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ParentId)
                                </td>
                               

                                <td>
                                    @Html.ActionLink("Cập nhật", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Chi tiết", "Detail", new { id = item.Id }) |
                                    @Html.ActionLink("Xóa", "Delete", new { id = item.Id })

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>